### ISSUE TITLE
Adas位置数据抽取

### ISSUE THREAD

**Issue by AceBear** [InCar/rooster-mr#2]
从阿里云OTS中抽取最近的位置信息存入mysql数据库中

+ 用java写成单独的jar包,当前先独立运行，以后被我们的第2代平台调用
+ 接受2个可调整参数，一个是车辆VIN码集合，另一个是时间段
+ 把由上述2个参数限定范围的数据（当前仅限位置数据）从阿里云OTS中，存入mysql数据库中
+ 可重入，程序可以多次执行，而结果相同

背景信息：
我们和以色列的Mobileye合作，Mobileye是业界领先的Adas公司
Mobileye设备把识别的信息通过三旗的通信模块，传送给我们的后台
我们的后台处理这些数据，供以后分析使用，尤其是UBI方面

当前，我们先把采集的数据存入OTS,一个阿里云的非关系型大数据存储
考虑到我们已经有一个基于mysql数据库的应用，为了快速给客户搭建演示
所以现在需要把OTS数据转储入mysql中，这样直接可以利用现有的平台

需要考虑一下性能，在测试期，只会有几台车辆的信息，但项目正式运转后
会有上万台车辆，百万级的数据量

时限：这是一个时间不太充分的任务，需要在2天内完成

**Comment by TeemolSparrow** [comment]
Deal
